import { z } from "zod";

export const askPreviewPayloadSchema = z.object({
  query: z.string().min(1),
  topK: z.number().int().min(1).max(20).optional(),
  mode: z.enum(["rag", "general"]).optional(),
});

export const confirmAskSavePayloadSchema = z.object({
  requestId: z.string().min(1),
  note: z.object({
    title: z.string().min(1),
    content: z.string().min(1),
    links: z.array(z.string()).optional(),
    tags: z.array(z.string()).optional(),
  }),
});

export const refactorPreviewPayloadSchema = z.object({
  path: z.string().min(1),
});

export const confirmRefactorSavePayloadSchema = z.object({
  requestId: z.string().min(1),
  sourcePath: z.string().min(1),
  note: z.object({
    title: z.string().min(1),
    content: z.string().min(1),
    links: z.array(z.string()).optional(),
    tags: z.array(z.string()).optional(),
  }),
});

export const reindexPayloadSchema = z.object({
  path: z.string().min(1),
});

export const synthesisPreviewPayloadSchema = z.object({
  topic: z.string().min(1),
  topK: z.number().int().min(1).max(20).optional(),
  noteIds: z.array(z.string()).optional(),
});

export const confirmSynthesisSavePayloadSchema = z.object({
  requestId: z.string().min(1),
  note: z.object({
    title: z.string().min(1),
    content: z.string().min(1),
    links: z.array(z.string()).optional(),
    tags: z.array(z.string()).optional(),
  }),
});

/**
 * The structured note shape generated by an LLM before a user explicitly
 * confirms that it should be written to the vault.
 */
export const generatedNoteSchema = z.object({
  title: z.string().trim().min(1),
  content: z.string().min(1),
  links: z.array(z.string().trim().min(1)).default([]),
  tags: z.array(z.string().trim().min(1)).default([]),
});

export const askModelResponseSchema = z.object({
  answer: z.string().trim().min(1),
  suggested_note: generatedNoteSchema,
  citations: z.array(z.number().int().positive()).default([]),
});

export const synthesisModelResponseSchema = z.object({
  note: generatedNoteSchema,
});

export type AskModelResponse = z.infer<typeof askModelResponseSchema>;
export type SynthesisModelResponse = z.infer<typeof synthesisModelResponseSchema>;

export const weakNotesPayloadSchema = z.object({
  minQualityScore: z.number().min(0).max(1).optional(),
  maxResults: z.number().int().min(1).max(200).optional(),
});

const aiTraceEvidenceSchema = z.object({
  documentId: z.string().uuid(),
  documentPath: z.string(),
  chunkIndex: z.number().int().nonnegative(),
  source: z.enum(["vector", "fts", "hybrid"]),
  score: z.number(),
  retrievalRank: z.number().int().positive(),
  selectionRank: z.number().int().positive().nullable(),
});

const aiTraceSpanSchema = z.object({
  id: z.string().uuid(),
  parentSpanId: z.string().uuid().nullable(),
  spanType: z.enum([
    "request",
    "policy",
    "retrieval",
    "reranking",
    "context_packing",
    "model",
    "tool",
    "retry",
    "final_answer",
  ]),
  status: z.enum(["started", "succeeded", "failed"]),
  attributes: z.record(z.string(), z.union([z.string(), z.number(), z.boolean(), z.null()])),
  errorCode: z.string().nullable(),
  startedAt: z.string().datetime(),
  completedAt: z.string().datetime().nullable(),
  durationMs: z.number().int().nonnegative().nullable(),
});

const aiTraceRunSchema = z.object({
  id: z.string().uuid(),
  traceVersion: z.string(),
  operation: z.enum(["ask", "synthesis", "bootstrap"]),
  policy: z.enum(["vault_hybrid", "selected_notes", "general_web", "no_retrieval"]),
  policyReason: z.string(),
  status: z.enum(["started", "succeeded", "failed"]),
  candidateCount: z.number().int().nonnegative(),
  selectedEvidenceCount: z.number().int().nonnegative(),
  contextCharacterCount: z.number().int().nonnegative(),
  modelProvider: z.string().nullable(),
  modelName: z.string().nullable(),
  promptVersion: z.string(),
  durationMs: z.number().int().nonnegative().nullable(),
  errorCode: z.string().nullable(),
  createdAt: z.string().datetime(),
  completedAt: z.string().datetime().nullable(),
  evidence: z.array(aiTraceEvidenceSchema).optional(),
  spans: z.array(aiTraceSpanSchema).optional(),
});

export const listAiTracesSchema = z
  .object({
    limit: z.number().int().min(1).max(100).optional(),
    cursor: z.string().min(1).max(512).optional(),
    includeEvidence: z.boolean().optional(),
  })
  .optional();
export const getAiTraceSchema = z.object({ traceId: z.string().uuid() });
export const aiTracePageSchema = z.object({
  items: z.array(aiTraceRunSchema),
  nextCursor: z.string().nullable(),
  totalCount: z.number().int().nonnegative(),
});
export const aiTraceDetailSchema = aiTraceRunSchema.nullable();
export type ListAiTracesInput = z.input<typeof listAiTracesSchema>;

const evaluationEvidenceSchema = z.object({
  documentPath: z.string().trim().min(1).max(400),
  chunkIndex: z.number().int().nonnegative().optional(),
});

export const createAiEvaluationDatasetSchema = z.object({
  name: z.string().trim().min(1).max(160),
  description: z.string().trim().max(2_000).optional(),
  /** Explicit acknowledgement: creating a durable case is an owner action. */
  approved: z.literal(true),
  cases: z
    .array(
      z.object({
        label: z.string().trim().min(1).max(160),
        redactedInput: z.string().trim().min(1).max(20_000),
        expectedEvidence: z.array(evaluationEvidenceSchema).max(100).default([]),
        expectedOutcome: z.string().trim().max(20_000).optional(),
        referenceAnswer: z.string().trim().max(20_000).optional(),
        candidateOutput: z.string().trim().max(40_000).optional(),
        retrievedEvidence: z.array(evaluationEvidenceSchema).max(100).default([]),
        /** Distinguishes an unavailable retrieval measurement from a measured empty result. */
        retrievalEvidenceEvaluated: z.boolean().default(false),
        /** Structural provenance only: the API does not read trace payload into this case. */
        sourceTraceId: z.string().uuid().optional(),
      }),
    )
    .min(1)
    .max(100),
});

export const runAiEvaluationSchema = z
  .object({
    datasetId: z.string().uuid(),
    judgeEnabled: z.boolean().default(false),
    /** Required when a judge could call the configured model provider. */
    confirmLlmJudge: z.boolean().default(false),
    maxCases: z.number().int().min(1).max(100).default(25),
    maxJudgeCalls: z.number().int().min(0).max(100).default(25),
    maxTotalTokens: z.number().int().min(1).max(100_000).default(20_000),
    rubricVersion: z.string().trim().min(1).max(80).default("groundedness-v1"),
  })
  .superRefine((value, context) => {
    if (value.judgeEnabled && !value.confirmLlmJudge)
      context.addIssue({
        code: z.ZodIssueCode.custom,
        message: "LLM judge runs require explicit confirmation",
        path: ["confirmLlmJudge"],
      });
  });

export const listAiEvaluationRunsSchema = z
  .object({ datasetId: z.string().uuid().optional() })
  .optional();
export const getAiEvaluationRunSchema = z.object({ runId: z.string().uuid() });
export const compareAiEvaluationRunsSchema = z
  .object({ baselineRunId: z.string().uuid(), candidateRunId: z.string().uuid() })
  .refine(
    (value) => value.baselineRunId !== value.candidateRunId,
    "Select two distinct evaluation runs",
  );

const aiEvaluationResultSchema = z.object({
  id: z.string().uuid(),
  caseId: z.string().uuid(),
  status: z.enum(["succeeded", "failed"]),
  deterministic: z.record(z.string(), z.unknown()),
  judgeScore: z.number().nullable(),
  judgeRationale: z.string().nullable(),
  promptTokens: z.number().int().nullable(),
  candidateTokens: z.number().int().nullable(),
  totalTokens: z.number().int().nullable(),
  errorCode: z.string().nullable(),
  createdAt: z.string().datetime(),
});
const aiEvaluationSpanSchema = z.object({
  id: z.string().uuid(),
  parentSpanId: z.string().uuid().nullable(),
  spanType: z.string(),
  status: z.enum(["started", "succeeded", "failed"]),
  attributes: z.record(z.string(), z.union([z.string(), z.number(), z.boolean(), z.null()])),
  errorCode: z.string().nullable(),
  startedAt: z.string().datetime(),
  completedAt: z.string().datetime().nullable(),
  durationMs: z.number().int().nullable(),
});
export const aiEvaluationDatasetSchema = z.object({
  id: z.string().uuid(),
  name: z.string(),
  description: z.string().nullable(),
  version: z.number().int(),
  approvedAt: z.string().datetime(),
  createdAt: z.string().datetime(),
  caseCount: z.number().int(),
});
export const aiEvaluationRunSchema = z.object({
  id: z.string().uuid(),
  datasetId: z.string().uuid(),
  datasetName: z.string(),
  datasetVersion: z.number().int(),
  evaluatorContractVersion: z.string(),
  rubricVersion: z.string(),
  judgeEnabled: z.boolean(),
  modelProvider: z.string().nullable(),
  modelName: z.string().nullable(),
  maxCases: z.number().int(),
  maxJudgeCalls: z.number().int(),
  maxTotalTokens: z.number().int(),
  status: z.enum(["started", "succeeded", "failed"]),
  errorCode: z.string().nullable(),
  summary: z.record(z.string(), z.unknown()),
  startedAt: z.string().datetime(),
  completedAt: z.string().datetime().nullable(),
  durationMs: z.number().int().nullable(),
  results: z.array(aiEvaluationResultSchema).optional(),
  spans: z.array(aiEvaluationSpanSchema).optional(),
});
export const aiEvaluationComparisonSchema = z.object({
  baseline: aiEvaluationRunSchema,
  candidate: aiEvaluationRunSchema,
  comparison: z.object({
    baselineRunId: z.string().uuid(),
    candidateRunId: z.string().uuid(),
    retrievalRecallDelta: z.number().nullable(),
    judgeScoreDelta: z.number().nullable(),
    failedCaseDelta: z.number().int(),
  }),
});

const httpUrlSchema = z
  .string()
  .url()
  .max(4_000)
  .refine((value) => /^https?:\/\//i.test(value), "Only http(s) URLs are allowed");

export const researchSourceSchema = z.object({
  title: z.string().trim().min(1).max(500),
  url: httpUrlSchema,
});

export const RESEARCH_CAPTURE_STATUS = {
  INBOX: "inbox",
  APPROVED: "approved",
  MERGED: "merged",
  DISCARDED: "discarded",
} as const;

export const RESEARCH_CAPTURE_ACTIVITY_EVENT = {
  CAPTURED: "captured",
  APPROVED: "approved",
  MERGED: "merged",
  DISCARDED: "discarded",
  INDEXING_FAILED: "indexing_failed",
  INDEXING_RETRIED: "indexing_retried",
} as const;

export const researchCaptureStatusSchema = z.enum([
  RESEARCH_CAPTURE_STATUS.INBOX,
  RESEARCH_CAPTURE_STATUS.APPROVED,
  RESEARCH_CAPTURE_STATUS.MERGED,
  RESEARCH_CAPTURE_STATUS.DISCARDED,
]);
export type ResearchCaptureStatus = z.infer<typeof researchCaptureStatusSchema>;

/** Payload accepted only from a locally paired desktop extension. */
export const extensionResearchCaptureSchema = z.object({
  sourceUrl: httpUrlSchema,
  sourceTitle: z.string().trim().min(1).max(500),
  query: z.string().trim().max(10_000).optional(),
  content: z.string().trim().min(1).max(100_000),
  sources: z.array(researchSourceSchema).max(100).default([]),
  capturedAt: z.string().datetime(),
});

export const approveResearchCaptureSchema = z.object({
  id: z.string().uuid(),
  title: z.string().trim().min(1).max(150).optional(),
  tags: z.array(z.string().trim().min(1).max(50)).max(20).optional(),
  destinationFolder: z
    .string()
    .trim()
    .min(1)
    .max(200)
    .regex(
      /^[a-zA-Z0-9][a-zA-Z0-9 _-]*(\/[a-zA-Z0-9][a-zA-Z0-9 _-]*)*$/,
      "Use a vault-relative folder path",
    )
    .optional(),
});

export const mergeResearchCaptureSchema = z.object({
  id: z.string().uuid(),
  targetDocumentId: z.string().uuid(),
});

export const retryResearchCaptureIndexSchema = z.object({
  id: z.string().uuid(),
});

export type ExtensionResearchCapture = z.infer<typeof extensionResearchCaptureSchema>;
export type ApproveResearchCapture = z.infer<typeof approveResearchCaptureSchema>;
export type MergeResearchCapture = z.infer<typeof mergeResearchCaptureSchema>;
export type RetryResearchCaptureIndex = z.infer<typeof retryResearchCaptureIndexSchema>;

export const qualityMetricsSchema = z.object({
  linkDensity: z.number().min(0).max(1),
  completeness: z.number().min(0).max(1),
  coherence: z.number().min(0).max(1).optional(),
  wordCount: z.number().int().min(0),
});

export type QualityMetrics = z.infer<typeof qualityMetricsSchema>;

export const organizationSuggestionTypeSchema = z.enum([
  "add_links",
  "complete_metadata",
  "expand_note",
  "review_duplicate",
  "review_stale_note",
]);

/**
 * A review-only recommendation derived from indexed metadata. It deliberately
 * excludes note content, embeddings, and generated changes.
 */
export const organizationSuggestionSchema = z.object({
  id: z.string().min(1),
  type: organizationSuggestionTypeSchema,
  noteId: z.string().uuid(),
  notePath: z.string().min(1),
  priority: z.number().min(0).max(1),
  confidence: z.number().min(0).max(1),
  reason: z.string().min(1),
  actionLabel: z.string().min(1),
  candidateNoteIds: z.array(z.string().uuid()),
  requiresApproval: z.literal(true),
  reversible: z.literal(true),
});

export const listOrganizationSuggestionsSchema = z
  .object({
    maxResults: z.number().int().min(1).max(200).optional(),
  })
  .optional();

export type ListOrganizationSuggestionsInput = z.input<typeof listOrganizationSuggestionsSchema>;
