import { z } from "zod";

export const askPreviewPayloadSchema = z.object({
  query: z.string().min(1),
  topK: z.number().int().min(1).max(20).optional(),
  mode: z.enum(["rag", "general"]).optional(),
});

export const confirmAskSavePayloadSchema = z.object({
  requestId: z.string().min(1),
  note: z.object({
    title: z.string().min(1),
    content: z.string().min(1),
    links: z.array(z.string()).optional(),
    tags: z.array(z.string()).optional(),
  }),
});

export const refactorPreviewPayloadSchema = z.object({
  path: z.string().min(1),
});

export const confirmRefactorSavePayloadSchema = z.object({
  requestId: z.string().min(1),
  sourcePath: z.string().min(1),
  note: z.object({
    title: z.string().min(1),
    content: z.string().min(1),
    links: z.array(z.string()).optional(),
    tags: z.array(z.string()).optional(),
  }),
});

export const reindexPayloadSchema = z.object({
  path: z.string().min(1),
});

export const synthesisPreviewPayloadSchema = z.object({
  topic: z.string().min(1),
  topK: z.number().int().min(1).max(20).optional(),
  noteIds: z.array(z.string()).optional(),
});

export const confirmSynthesisSavePayloadSchema = z.object({
  requestId: z.string().min(1),
  note: z.object({
    title: z.string().min(1),
    content: z.string().min(1),
    links: z.array(z.string()).optional(),
    tags: z.array(z.string()).optional(),
  }),
});

/**
 * The structured note shape generated by an LLM before a user explicitly
 * confirms that it should be written to the vault.
 */
export const generatedNoteSchema = z.object({
  title: z.string().trim().min(1),
  content: z.string().min(1),
  links: z.array(z.string().trim().min(1)).default([]),
  tags: z.array(z.string().trim().min(1)).default([]),
});

export const askModelResponseSchema = z.object({
  answer: z.string().trim().min(1),
  suggested_note: generatedNoteSchema,
  citations: z.array(z.number().int().positive()).default([]),
});

export const synthesisModelResponseSchema = z.object({
  note: generatedNoteSchema,
});

export type AskModelResponse = z.infer<typeof askModelResponseSchema>;
export type SynthesisModelResponse = z.infer<typeof synthesisModelResponseSchema>;

export const weakNotesPayloadSchema = z.object({
  minQualityScore: z.number().min(0).max(1).optional(),
  maxResults: z.number().int().min(1).max(200).optional(),
});

const aiTraceEvidenceSchema = z.object({
  documentId: z.string().uuid(),
  documentPath: z.string(),
  chunkIndex: z.number().int().nonnegative(),
  source: z.enum(["vector", "fts", "hybrid"]),
  score: z.number(),
  retrievalRank: z.number().int().positive(),
  selectionRank: z.number().int().positive().nullable(),
});

const aiTraceSpanSchema = z.object({
  id: z.string().uuid(),
  parentSpanId: z.string().uuid().nullable(),
  spanType: z.enum(["request", "policy", "retrieval", "reranking", "context_packing", "model", "tool", "retry", "final_answer"]),
  status: z.enum(["started", "succeeded", "failed"]),
  attributes: z.record(z.string(), z.union([z.string(), z.number(), z.boolean(), z.null()])),
  errorCode: z.string().nullable(),
  startedAt: z.string().datetime(),
  completedAt: z.string().datetime().nullable(),
  durationMs: z.number().int().nonnegative().nullable(),
});

const aiTraceRunSchema = z.object({
  id: z.string().uuid(),
  traceVersion: z.string(),
  operation: z.enum(["ask", "synthesis", "bootstrap"]),
  policy: z.enum(["vault_hybrid", "selected_notes", "general_web", "no_retrieval"]),
  policyReason: z.string(),
  status: z.enum(["started", "succeeded", "failed"]),
  candidateCount: z.number().int().nonnegative(),
  selectedEvidenceCount: z.number().int().nonnegative(),
  contextCharacterCount: z.number().int().nonnegative(),
  modelProvider: z.string().nullable(),
  modelName: z.string().nullable(),
  promptVersion: z.string(),
  durationMs: z.number().int().nonnegative().nullable(),
  errorCode: z.string().nullable(),
  createdAt: z.string().datetime(),
  completedAt: z.string().datetime().nullable(),
  evidence: z.array(aiTraceEvidenceSchema).optional(),
  spans: z.array(aiTraceSpanSchema).optional(),
});

export const listAiTracesSchema = z.object({
  limit: z.number().int().min(1).max(100).optional(),
  cursor: z.string().min(1).max(512).optional(),
  includeEvidence: z.boolean().optional(),
}).optional();
export const getAiTraceSchema = z.object({ traceId: z.string().uuid() });
export const aiTracePageSchema = z.object({
  items: z.array(aiTraceRunSchema),
  nextCursor: z.string().nullable(),
});
export const aiTraceDetailSchema = aiTraceRunSchema.nullable();
export type ListAiTracesInput = z.input<typeof listAiTracesSchema>;

const httpUrlSchema = z.string().url().max(4_000).refine(
  (value) => /^https?:\/\//i.test(value),
  "Only http(s) URLs are allowed"
);

export const researchSourceSchema = z.object({
  title: z.string().trim().min(1).max(500),
  url: httpUrlSchema,
});

export const RESEARCH_CAPTURE_STATUS = {
  INBOX: "inbox",
  APPROVED: "approved",
  MERGED: "merged",
  DISCARDED: "discarded",
} as const;

export const RESEARCH_CAPTURE_ACTIVITY_EVENT = {
  CAPTURED: "captured",
  APPROVED: "approved",
  MERGED: "merged",
  DISCARDED: "discarded",
  INDEXING_FAILED: "indexing_failed",
  INDEXING_RETRIED: "indexing_retried",
} as const;

export const researchCaptureStatusSchema = z.enum([
  RESEARCH_CAPTURE_STATUS.INBOX,
  RESEARCH_CAPTURE_STATUS.APPROVED,
  RESEARCH_CAPTURE_STATUS.MERGED,
  RESEARCH_CAPTURE_STATUS.DISCARDED,
]);
export type ResearchCaptureStatus = z.infer<typeof researchCaptureStatusSchema>;

/** Payload accepted only from a locally paired desktop extension. */
export const extensionResearchCaptureSchema = z.object({
  sourceUrl: httpUrlSchema,
  sourceTitle: z.string().trim().min(1).max(500),
  query: z.string().trim().max(10_000).optional(),
  content: z.string().trim().min(1).max(100_000),
  sources: z.array(researchSourceSchema).max(100).default([]),
  capturedAt: z.string().datetime(),
});

export const approveResearchCaptureSchema = z.object({
  id: z.string().uuid(),
  title: z.string().trim().min(1).max(150).optional(),
  tags: z.array(z.string().trim().min(1).max(50)).max(20).optional(),
  destinationFolder: z.string().trim().min(1).max(200).regex(/^[a-zA-Z0-9][a-zA-Z0-9 _-]*(\/[a-zA-Z0-9][a-zA-Z0-9 _-]*)*$/, 'Use a vault-relative folder path').optional(),
});

export const mergeResearchCaptureSchema = z.object({
  id: z.string().uuid(),
  targetDocumentId: z.string().uuid(),
});

export const retryResearchCaptureIndexSchema = z.object({
  id: z.string().uuid(),
});

export type ExtensionResearchCapture = z.infer<typeof extensionResearchCaptureSchema>;
export type ApproveResearchCapture = z.infer<typeof approveResearchCaptureSchema>;
export type MergeResearchCapture = z.infer<typeof mergeResearchCaptureSchema>;
export type RetryResearchCaptureIndex = z.infer<typeof retryResearchCaptureIndexSchema>;

export const qualityMetricsSchema = z.object({
  linkDensity: z.number().min(0).max(1),
  completeness: z.number().min(0).max(1),
  coherence: z.number().min(0).max(1).optional(),
  wordCount: z.number().int().min(0),
});

export type QualityMetrics = z.infer<typeof qualityMetricsSchema>;

export const organizationSuggestionTypeSchema = z.enum([
  "add_links",
  "complete_metadata",
  "expand_note",
  "review_duplicate",
  "review_stale_note",
]);

/**
 * A review-only recommendation derived from indexed metadata. It deliberately
 * excludes note content, embeddings, and generated changes.
 */
export const organizationSuggestionSchema = z.object({
  id: z.string().min(1),
  type: organizationSuggestionTypeSchema,
  noteId: z.string().uuid(),
  notePath: z.string().min(1),
  priority: z.number().min(0).max(1),
  confidence: z.number().min(0).max(1),
  reason: z.string().min(1),
  actionLabel: z.string().min(1),
  candidateNoteIds: z.array(z.string().uuid()),
  requiresApproval: z.literal(true),
  reversible: z.literal(true),
});

export const listOrganizationSuggestionsSchema = z.object({
  maxResults: z.number().int().min(1).max(200).optional(),
}).optional();

export type ListOrganizationSuggestionsInput = z.input<typeof listOrganizationSuggestionsSchema>;
